import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton,  UserButton, useUser} from "@clerk/nextjs";
import { api } from "~/utils/api";
import { Button } from "~/components/ui/button";

const Home: NextPage = () => {
  const {data} = api.posts.getAll.useQuery();
  console.log(data)
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!!user.isSignedIn && <UserButton />}
          {!user.isSignedIn && (
            <SignInButton mode="modal">
              <Button>Sign in</Button>
            </SignInButton>
          )}
          <div className="m-4 flex flex-col">
            {data?.map((post) => (
              <div
                key={post.id}
                className="m-4 flex flex-col rounded-md bg-primary p-4 shadow-lg"
              >
                <p className="font-sans leading-7 [&:not(:first-child)]:mt-6">
                  post
                </p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
